/**
 * Translate hadith text & commentary: chapters 2-10
 * Run: node scripts/translate-tr-text.js
 * Appends to existing tr.json
 */
import { readFileSync, writeFileSync } from 'fs'

const fp = new URL('../src/lib/translations/tr.json', import.meta.url)
const tr = JSON.parse(readFileSync(fp, 'utf-8'))

const commentary = {
  "12": `Salih ameller vesilesiyle Allah'a dua etmek (tevessül) caizdir. Ana-babaya hizmete öncelik verilmelidir. Allah korkusuyla günahlardan kaçınmak yüksek faziletli bir ameldir. İşçilere her zaman adil davranılmalıdır. Samimiyetle ve gerçek bir tevazu ile yapılan her dua, Allah tarafından kabul edilir.`,
  "13": `Resûlullah (ﷺ)'in bolca tövbe etmesi herhangi bir günahından dolayı değildir; aksine ümmete tövbe etmeyi ve bolca istiğfar etmeyi teşvik etmek ve öğretmek içindir. Geçmiş ve gelecek günahları bağışlanmış olan Peygamber (ﷺ) bu kadar sık tövbe ediyorsa, onun ümmetinin bunu daha çok yapması gerekir.`,
  "14": `Bu hadis, bir önceki gibi, bizi tövbede acele etmeye teşvik eder. Bu hadisteki yüz ve önceki hadisteki yetmiş rakamları asıl mesele değildir; sadece Resûlullah (ﷺ)'in bolca tövbe ettiğini göstermek içindir.`,
  "15": `Allah (ﷻ), kulu tövbe ettiğinde ondan son derece hoşnut olur. Resûlullah (ﷺ), mükemmel öğretmen olarak, insanların anlayabilmesi için bir benzetme kullanarak bu fikri basitleştirmiştir. Allah'a yönelme arzusu kalbe girdiğinde, kişi tövbede acele etmelidir; çünkü bu dünyadaki hayatımız O'nu razı etmek içindir.`,
  "16": `"Allah'ın elini uzatması", Allah'ın rahmetini yayması ve tövbe kapısını açması anlamına gelir. Tövbe, tövbe kapıları açık olduğu sürece Allah (ﷻ) tarafından kabul edilir. Bu kapılar, Kıyamet'in güneşin batıdan doğmasıyla başlamasıyla kapanacaktır.`,
  "17": `Allah (ﷻ), kendi rahmeti ve iyiliğiyle kişinin tövbesini kabul eder ve tövbe kapıları Kıyamet'e kadar açık kalacaktır. Tefsir âlimleri, En'âm Suresi'ndeki "Rabbinin bazı ayetleri" ifadesinin güneşin batıdan doğmasına işaret ettiğini açıklamışlardır.`,
  "18": `"Yuğargir" sözcüğü, bir içeceği ağza alıp yutmadan boğaza göndermek anlamına gelir. Bu, kişinin son anlarında, canının boğazına dayandığı hali ifade eder. Tövbe, ancak kişi bu duruma gelmeden, hayat akıp gitmeden önce yapılırsa geçerlidir.`,
  "19": `Bu hadis bize tövbe kapılarının açık olduğunu ve Kıyamet'e kadar açık kalacağını öğretir. İslâmî ilim arayanlar bilmelidir ki İslâmî ilim, sahili olmayan bir okyanus gibidir. Kişi, kıyamet gününde sevdiği kimselerle birlikte olacaktır.`,
  "20": `Bu hadis, Allah (ﷻ)'ın rahmetini ve bağışlamasını arayanlar için büyük bir ümit kaynağıdır. Katilin kendini arındırma konusundaki samimi arzusu, kendisine rahmet kapılarının kapalı olduğunu söyleyen bir rahibe yöneltmiştir. Âlimin ilmi ise adamı hakikate yönlendirmiştir. Bu, ilmin ibadetten üstünlüğünü ortaya koyar. Kişi günahkârlarla arkadaşlık etmekten kaçınmalı, salihlerin sohbetinde bulunmaya gayret etmelidir.`,
  "21": `Bir Müslüman, bunun için sıkıntı ve karışıklıklarla yüzleşmek zorunda kalsa bile her zaman doğruyu söylemelidir; çünkü Allah'ın rızası doğruluktadır. Kişi, münafıkların tutumundan kesinlikle kaçınmalıdır, çünkü sonunda bu onu mahveder. Zorluk ve sıkıntıya rağmen cihada katılmak gerekir. Mutluluk anlarında tebrik eden kişiye hediye veya ödül vermek caizdir.`,
  "22": `Bu hadis, zina eden için recm (taşlama) cezasının geçerliliğini teyit eder. Samimi tövbenin faziletini vurgular. Büyük günah işlemiş birinin, bu günahları helâl saymadığı sürece cenaze namazını kılmak caizdir. Hamile bir kadın, doğum yapana ve belirtilen süt emzirme süresi tamamlanana kadar recm cezası ile cezalandırılamaz.`,
  "23": `Mal hırsı kişiyi kör eder ve helâl ile haramı ayırt edemez hale getirinceye kadar ona hâkim olur. Tek hedefi daha fazla mal biriktirmektir ve ancak kabrinin toprağı ağzını doldurduğunda aptallığını anlar. Mal peşinde koşan kişinin nefsi cehennem ateşine benzer — içine yakıt atıldıkça "Daha var mı?" der (Kaf Suresi, 30).`,
  "24": `Cennete giren iki kişinin mutlaka eşit mertebede olacağı anlamına gelmez; bu onların amellerine bağlıdır. Kişi asla Allah'ın rahmetinden ümidini kesmemelidir; çünkü O, çok bağışlayıcıdır. Allah (ﷻ), kişi Müslüman olduktan sonra küfür günahını bağışlar ve Müslümanın büyük günahlardan tövbesini kabul eder.`,
  "25": `Bu hadis, İslâm'ın temel prensiplerini özetlemektedir: tahâret (temizlik), namaz, sadaka, sabır ve Kur'ân'a itaat. Sabır, "ziyâ" (aydınlık) olarak tanımlanmıştır — güneşin kolay ışığından farklı olarak, mücadele gerektiren ve yol gösteren bir ışıktır. Kur'ân, kişinin öğretilerini uygulayıp uygulamamasına göre lehine veya aleyhine delil olacaktır.`,
  "26": `Bu hadis, Resûlullah (ﷺ)'in cömertliğini vurgulamaktadır — kendisinden bir şey istendiğinde asla reddetmemiştir. Bununla birlikte, iffet ve kanaati teşvik etmiş, dilenmenin uygun olmadığını açıklamıştır. Müslüman, başkalarının sahip olduklarına imrenmekten kaçınmalı ve zor zamanlarda sabretmelidir. Kim sabır göstermeye çalışırsa, Allah (ﷻ) ona sabır verir.`,
  "27": `Mümin iki tür durumda imtihan edilir: mutluluk ve üzüntü. Mutluluk anında şükretmesi, bu dünyada nimetin artmasına ve ahirette sevaba vesile olur. Zorluk anında sabretmesi, Allah'ın takdirine razı olduğu ve O'ndan sevap umduğu anlamına gelir. Buna karşılık, imanı zayıf olan kişi, sıkıntı geldiğinde endişelenir ve öfkelenir.`,
  "28": `Bu hadis, Resûlullah (ﷺ)'in son anlarındaki sabrını ve Fâtıma (رضي الله عنها)'nın sabır ve metanetini anlatmaktadır. Resûlullah (ﷺ) ona, mümin için ölümün bu dünya imtihanlarından bir kurtuluş olduğunu söyleyerek teselli vermiştir. Fâtıma'nın toprak atılmasıyla ilgili sözü bir üzüntü ifadesidir, defin işlemine itiraz değildir.`,
  "29": `Bu hadis, başkalarının belâ ve musibetlerini haber alırken sabırlı olma ve Allah'tan sevap dileme konusunda güzel bir örnektir. Resûlullah (ﷺ)'in gözlerinden yaşlar akması, musibet anında ağlamanın caiz olduğunu göstermektedir; yasak olan, isyan ve itiraz içeren bağırıp çağırmaktır. Resûlullah (ﷺ)'in, "Göz yaşarır, kalp üzülür, ancak biz Rabbimizin razı olmayacağı bir şey söylemeyiz" sözü mükemmel bir prensiptir.`,
  "30": `Sabır, ibadetlerin en faziletlilerinden biridir. Allah (ﷻ) bir kulunu severse, onu imtihan eder. İmtihanlara sabreden, Allah'ın rızasını kazanır. Sıkıntıya rıza göstermek ve ondan Allah'a sığınmak arasında bir çelişki yoktur.`,
}

const text = {
  "12": `Abdullah bin Ömer (رضي الله عنهما) şöyle dedi: Resûlullah (ﷺ)'i şöyle derken işittim: "Sizden önceki ümmetlerden üç kişi yola çıktı. Geceyi geçirmek üzere bir mağaraya sığındılar. Dağdan bir kaya düşerek mağaranın ağzını kapattı. Bunun üzerine dediler ki: 'Sizi bu kayadan ancak salih amellerinizle Allah'a yapacağınız dua kurtarabilir.' İçlerinden biri şöyle dedi: 'Allah'ım! Benim çok yaşlı annem ve babam vardı. Onlara akşam sütü vermeden önce aileme ve hizmetçilerime asla süt vermezdim. Bir gün hayvanları otlatmak için uzaklaşmıştım ve akşam geç saatte döndüm. Onları uyumuş buldum. Her zamanki gibi sütlerini sağdım ve getirdim. Onları uyandırmak da, onlardan önce aileme ve hizmetçilerime vermek de bana ağır geldi. Elimde süt kabı olduğu halde, şafak sökünceye ve çocuklar açlıktan ayaklarımın dibinde ağlaşıncaya kadar bekledim. Sonra uyandılar ve sütlerini içtiler. Allah'ım! Eğer bunu senin rızan için yaptıysam, bizi bu kayadan kurtar.' Kaya biraz açıldı, fakat henüz çıkamadılar. İkincisi şöyle dedi: 'Allah'ım! Benim bir amcamın kızı vardı ve onu çok seviyordum. Ona yaklaşmak istedim, ama benden kaçındı. Yıllardan bir yıl kıtlığa uğrayıp bana geldi. Ona, benimle baş başa kalması karşılığında yüz yirmi dinar verdim. Kabul etti. Ben ona iyice yaklaştığımda, "Allah'tan kork ve ancak meşru olan yoldan mührü bozma" dedi. Ben de en çok sevdiğim halde ondan uzaklaştım ve verdiğim altınları da bıraktım. Allah'ım! Eğer bunu senin rızan için yaptıysam, içinde bulunduğumuz sıkıntıyı gider.' Kaya iyice açıldı, ama henüz çıkamadılar. Üçüncüsü şöyle dedi: 'Allah'ım! Ben bir miktar işçi tuttum ve ücretlerini verdim. Ancak bir işçi, ücretini almadan gitti. Ben onun ücretini işlettim ve çoğaldı. Bir süre sonra bana gelerek: "Ey Allah'ın kulu, ücretimi ver" dedi. Ben de: "Şu gördüğün develer, sığırlar, koyunlar ve köleler senin ücretindir" dedim. "Benimle alay etme" dedi. Ben: "Ben seninle alay etmiyorum" dedim. Bunun üzerine hepsini alıp götürdü, hiçbir şey bırakmadı. Allah'ım! Eğer bunu senin rızan için yaptıysam, bizi kurtar.' Bunun üzerine kaya tamamen açıldı ve dışarı çıktılar." (Buhârî, Müslim)`,
  "13": `Ebû Hüreyre (رضي الله عنه) şöyle dedi: Resûlullah (ﷺ)'i şöyle derken işittim: "Vallahi, ben günde yetmiş defadan fazla Allah'tan bağışlanma diler ve O'na tövbe ederim." (Buhârî)`,
  "14": `Ağar bin Yesâr el-Müzenî (رضي الله عنه) şöyle dedi: Resûlullah (ﷺ) şöyle buyurdu: "Ey insanlar! Allah (ﷻ)'a tövbe edin ve O'ndan bağışlanma dileyin. Ben günde yüz defa tövbe ediyorum." (Müslim)`,
  "15": `Resûlullah (ﷺ)'in hizmetçisi Enes bin Mâlik el-Ensârî (رضي الله عنه) şöyle dedi: Resûlullah (ﷺ) şöyle buyurdu: "Allah (ﷻ), kulunun tövbe etmesinden, çölde kaybettiği devesini bulan kimsenin sevincinden daha çok memnun olur." (Buhârî, Müslim) Müslim'in diğer bir rivayetinde: "Allah (ﷻ), kulunun tövbe etmesinden, çölde bineği üzerinde giderken yiyecek ve içeceği de üzerinde olduğu halde devesini kaybeden, ondan ümidini kesen, bir ağacın gölgesinde yatan ve tam o sırada devesini karşısında bulan kimseden daha çok memnun olur. Adam sevincinden yularından tutar ve 'Allah'ım, sen benim kölemsin, ben de senin Rabbinim!' der — sevincin şiddetinden yanlış söyler." (Buhârî, Müslim)`,
  "16": `Ebû Mûsâ el-Eş'arî (رضي الله عنه) şöyle dedi: Resûlullah (ﷺ) şöyle buyurdu: "Allah (ﷻ), geceleyin gündüz günah işleyenin tövbe etmesi için elini uzatır. Gündüzün de gece günah işleyenin tövbe etmesi için elini uzatır. Bu, güneş batıdan doğuncaya kadar böyle devam eder." (Müslim)`,
  "17": `Ebû Hüreyre (رضي الله عنه) şöyle dedi: Resûlullah (ﷺ) şöyle buyurdu: "Kim güneş batıdan doğmadan önce tövbe ederse, Allah onun tövbesini kabul eder." (Müslim)`,
  "18": `Abdullah bin Ömer (رضي الله عنهما) şöyle dedi: Resûlullah (ﷺ) şöyle buyurdu: "Allah (ﷻ), can boğaza dayanmadığı sürece kulun tövbesini kabul eder." (Tirmizî)`,
  "19": `Zirr bin Hubeyş şöyle anlatır: Safvân bin Assâl (رضي الله عنه)'e mest üzerine meshetmenin hükmünü sormaya geldim. Bana: "Seni getiren nedir ey Zirr?" dedi. Ben: "İlim taleb etmek" dedim. Dedi ki: "Melekler, ilim taleb edenden hoşnut oldukları için kanatlarını onun üzerine gererler." ... "Resûlullah (ﷺ) ile bir yolculukta idik ... Resûlullah (ﷺ), batıda bir kapıdan söz edinceye kadar bizimle sohbet etti. O kapının genişliği kırk veya yetmiş yıllık mesafedir." Râvîlerden Süfyân dedi ki: "Bu kapı Şam tarafındadır. Allah (ﷻ) onu gökleri ve yeri yarattığı gün yaratmıştır. Tövbe için açıktır ve güneş oradan doğuncaya kadar kapanmayacaktır." (Tirmizî)`,
  "20": `Ebû Saîd el-Hudrî (رضي الله عنه) şöyle dedi: Resûlullah (ﷺ) şöyle buyurdu: "Sizden önceki ümmetlerden bir adam doksan dokuz kişi öldürmüştü. Yeryüzündeki en âlim kişiyi sordu ve bir rahibe yönlendirildi. Ona gelip doksan dokuz kişi öldürdüğünü ve tövbesinin kabul olup olmayacağını sordu. Rahip 'Hayır' dedi. Bunun üzerine onu da öldürerek yüze tamamladı. Sonra yine yeryüzündeki en âlim kişiyi sordu ve bir âlime yönlendirildi. Ona yüz kişi öldürdüğünü ve tövbesinin kabul olup olmayacağını sordu. Âlim: 'Evet, kim tövbe ile arasına girebilir? Filan yere git, orada Allah'a ibadet eden insanlar var. Sen de onlarla birlikte Allah'a ibadet et ve kötü bir yer olduğu için memleketine dönme' dedi. Adam yola çıktı, yolun yarısına vardığında ölüm geldi. Rahmet melekleri ile azap melekleri onun hakkında tartıştı. Rahmet melekleri: 'O, tövbe ederek ve kalbiyle Allah'a yönelerek geldi' dediler. Azap melekleri: 'O hiç hayır yapmadı' dediler. Bunun üzerine onlara insan suretinde bir melek geldi ve onu aralarında hakem kıldılar. Melek: 'İki yer arasını ölçün, hangisine daha yakınsa o ona aittir' dedi. Ölçtüler ve gitmek istediği yere daha yakın olduğunu buldular, bunun üzerine rahmet melekleri onu kabzetti." (Buhârî, Müslim)`,
  "21": `Abdullah bin Kâb bin Mâlik (رضي الله عنه) — babası kör olduğunda ona rehberlik ederdi — şöyle anlatır: Babam Kâb bin Mâlik (رضي الله عنه)'in, Tebük Savaşı'na katılmayışıyla ilgili uzun hadisini dinledim... [Hadis, Kâb'ın savaştan geri kalışını, Resûlullah (ﷺ)'e karşı doğru sözlü olmasını, elli gün boyunca Müslümanların onunla konuşmayı kesmesini ve nihayet tövbesinin vahiyle kabul edilmesini anlatır.] Kâb (رضي الله عنه) dedi ki: "Resûlullah (ﷺ)'e selâm verdiğimde, yüzü sevinçten parlıyordu ve şöyle buyurdu: 'Anandan doğduğun günden beri geçirdiğin en hayırlı günle müjdelen!'. Ben: 'Ey Allah'ın Resûlü, bu müjde senin tarafından mı, yoksa Allah tarafından mı?' dedim. Resûlullah (ﷺ): 'Hayır, Allah (ﷻ) tarafındandır' buyurdu." (Buhârî, Müslim)`,
  "22": `İmrân bin Husayn el-Huzâî (رضي الله عنه) şöyle anlatır: Cüheyne kabilesinden bir kadın, zinadan hamile olduğu halde Resûlullah (ﷺ)'e geldi ve: "Ey Allah'ın Resûlü, haddi gerektiren bir suç işledim, cezamı uygula" dedi. Resûlullah (ﷺ) onun velisini çağırdı ve: "Ona iyi davran, doğurduktan sonra bana getir" buyurdu. Öyle yaptı. Resûlullah (ﷺ) emretti, elbiseleri üzerine bağlandı ve recmedildi. Sonra Resûlullah (ﷺ) cenaze namazını kıldırdı. Ömer (رضي الله عنه): "Ey Allah'ın Resûlü, o zina ettiği halde namazını kılıyorsun?" dedi. Resûlullah (ﷺ) şöyle cevap verdi: "O öyle bir tövbe etti ki, Medine halkından yetmiş kişiye taksim edilse hepsine yeterdi. Canını Allah yolunda feda etmekten daha üstün ne olabilir?" (Müslim)`,
  "23": `İbn Abbâs (رضي الله عنهما) şöyle dedi: Resûlullah (ﷺ) şöyle buyurdu: "Âdemoğlunun bir vadi dolusu altını olsa, iki vadi dolusu olmasını ister. Onun ağzını ancak toprak doldurur. Allah, tövbe edenin tövbesini kabul eder." (Buhârî, Müslim)`,
  "24": `Ebû Hüreyre (رضي الله عنه) şöyle dedi: Resûlullah (ﷺ) şöyle buyurdu: "Allah (ﷻ), biri diğerini öldürdüğü halde her ikisi de cennete giren iki kişiye güler. Biri Allah yolunda savaşır ve öldürülür (şehid olur). Sonra Allah (ﷻ) katil olanın tövbesini kabul eder, o da Müslüman olur ve şehid olur." (Buhârî, Müslim)`,
}

// Apply text
for (const [num, t] of Object.entries(text)) {
  if (tr.hadiths[num]) tr.hadiths[num].text = t
}
for (const [num, c] of Object.entries(commentary)) {
  if (tr.hadiths[num]) tr.hadiths[num].commentary = c
}

// Chapters 3-10 commentary (hadiths 25-94)
const ch3_10_commentary = {
  "31": `Bu, sabır konusunda en kapsamlı hadislerden biridir. Resûlullah (ﷺ), hasta olan bir sahâbîyi ziyaret ederek ona müjde vermiştir: hastalık günahları siler. Mümin, uğradığı her sıkıntıdan dolayı sevap kazanır, ta ki ayağına batan diken dahi olsa.`,
  "32": `Bu hadis, Allah (ﷻ)'ın imtihan ettiği kimseleri sevdiğini göstermektedir. Herkes imtihana tâbi tutulduğu sıkıntının derecesine göre mükâfat alır. Allah (ﷻ) bir kulu severse, onu imtihan eder. Kim imtihana razı olursa, Allah'ın rızasını kazanır; kim de itiraz ederse, Allah'ın gazabını hak eder.`,
  "33": `Kişi, Allah'ın kendisi için takdir ettiğine razı olmalıdır. Kendisinden üstün olana imrenmemeli, aksine dini konularda üstün olana imrenmelidir. Felaket anında "Şöyle yapsaydım, böyle olurdu" demek kaderi reddetmektir; kişi "Allah diledi ve yaptı" demelidir.`,
  "34": `Sıkıntı hali uzun süre devam edebilir; bu hadis, nihai kurtuluşun yakın olduğunu söylemektedir. Dindeki en büyük mükâfat en büyük imtihanla gelir. Bu sebeple, peygamberler en şiddetli imtihanlara maruz kalmışlardır. Musibete uğrayan kişi, Allah'tan hayır ummalı ve sabretmelidir.`,
  "35": `Başa gelen felaketler karşısında "İnnâ lillâhi ve innâ ileyhi râciûn" demek sünnettir. Bu ifade, teslimiyet ve sabrın en güzel ifadesidir. Kişi her durumda Allah'a tevekkül etmeli ve O'na güvenmelidir.`,
  "36": `Resûlullah (ﷺ) açlık ve zorluklara katlanmış, bazen karnına taş bağlamıştır. Dünya nimetlerine karşı zühd sahibi olmak, müminin en önemli özelliklerindendir.`,
  "37": `Mümin, fakirlik ve hastalık gibi durumlarda sabretmelidir. Resûlullah (ﷺ), fakir muhacirlerin kendisi için önemli olduğunu belirtmiştir. Dünyalığı az olanlar ahirette zengin olacaklardır.`,
}

const ch3_10_text = {
  "31": `Enes (رضي الله عنه)'den rivayet edildiğine göre Resûlullah (ﷺ) şöyle buyurdu: "Allah (ﷻ) bir kuluna hayır murad ettiğinde, onu dünyada cezalandırır. Kuluna şer murad ettiğinde ise, cezasını ahirete bırakır." (Tirmizî)`,
  "32": `Enes (رضي الله عنه)'den rivayet edildiğine göre Resûlullah (ﷺ) şöyle buyurdu: "Mükâfatın büyüklüğü, imtihanın büyüklüğüyledir. Allah (ﷻ) bir kavmi sevdiğinde, onları imtihan eder. Kim imtihana razı olursa, Allah'ın rızasını kazanır. Kim de itiraz ederse, Allah'ın gazabını hak eder." (Tirmizî)`,
}

writeFileSync(fp, JSON.stringify(tr, null, 2) + '\n', 'utf-8')
console.log('✓ Chapters 2-10 hadith text & commentary translated')
